### PR TITLE
chore(dependencies): update dependencies as the current setup does not work with node 0.12.0

### PR DESCRIPTION
**Pull request by nikgraf**
Here the initial error:

```
node_modules/coffee-script/lib/coffee-script/register.js:33
        curExtension = '.' + extensions.join('.');
                       ^
Error: Module did not self-register.
```

### CODE REVIEW

**Comment by nikgraf** [comment]
I couldn't get protractor to run, but I never did before. Can someone check if it still works?

**Comment by Maqsim** [comment]
@nikgraf Did you run a selenium webdriver before `gulp protractor`?

**Comment by nikgraf** [comment]
@Maqsim that was my issue, I couldn't get selenium to run. It didn't find Chrome. I also tried FF, but didn't work as well. Probably some issues with my local environment.

**Comment by dmitryevseev** [comment]
@nikgraf Thanks. Works fine with both 0.10 and 0.12. Protractor works fine as well - you need to have selenium server running

**Pull request merged**
