### PR TITLE
added font-awesome

### PR DESCRIPTION
**Pull request by julesbou**

### CODE REVIEW

**Comment by dmitryevseev** [comment]
Hey @julesbou I have a couple of remarks:
1. not sure if it should be introduced in the seed as icons are often project specific
2. font-awesome can be installed with bower

**Comment by dmitryevseev** [comment]
Synced with borodean on that. We agreed on this features quite specific for the seed

**Comment by borodean** [comment]
One more thought.

For now we have 2 options to decide for each project: using some third-party icon library like Font Awesome or generating our owns with grunt-webfont. Using both is like too much, so ideally only one should be picked.

The grunt-webfont way is more flexible and easily tuned to much the specifics of a particular project, while third-party libraries are great for bootstrapping w/o designs.

What I think would probably reach both objectives is having grunt-webfont preinstalled with some basic icons for it that can be used for bootstrapping and than replaced with the designed ones. Because than we would not be forced to switch from a third-party library to grunt-webfont in the middle of the process (to follow increasing requirements) it would keep the workflow intact.

**Comment by julesbou** [comment]
Oops i missed this discussion. for me font-awesome is a big win, i have all [these icons available](http://fontawesome.io/icons/) just by adding a css classname to an element, makes me win lot of time, and fontawesome really has a LOT of icons. Why reinventing the wheel :)

**Comment by dmitryevseev** [comment]
Yeah, as soon as you need the icons it's the good tool, and can be introduced easily. But as for the core it's really not a requirement.

**Pull request closed without merging**
